# Generated by Django 4.0.5 on 2022-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('hardness', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
