# Generated by Django 4.0.5 on 2022-07-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_crystal_delete_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cleansing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('S', 'Smudging'), ('W', 'Running Water'), ('M', 'Full Moon'), ('O', 'Other')], default='S', max_length=1)),
                ('crystal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.crystal')),
            ],
        ),
    ]
