# Generated by Django 4.0.5 on 2022-07-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_location_cleansing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleansing',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='crystal',
            name='location',
            field=models.ManyToManyField(to='main_app.location'),
        ),
        migrations.AlterField(
            model_name='cleansing',
            name='date',
            field=models.DateField(verbose_name='cleansing date'),
        ),
    ]
